project:
  type: website

website:
  title: "Catalina Cañizares"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - projects.qmd
      - teaching.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto