project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-KWC93SV91C" 
  cookie-consent: true
  title: "Catalina Cañizares"
  site-url: https://ccani007.github.io/ccani_website/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - projects.qmd
      - teaching.qmd
  page-footer:
    left: |
      <span class="container"><strong>Made with [Posit Quarto](https://quarto.org/){target="_blank"}</strong></span>
    right: |
      <span class="container"><strong>[Github Repo](https://github.com/ccani007/ccani_website){target="_blank"}</strong></span>
    background: "#2c3c54"
    
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    
  