project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-KWC93SV91C" 
  cookie-consent: true
  title: "Catalina Cañizares"
  site-url: https://ccani007.github.io/ccani_website/
  navbar:
    right:
     - href: index.qmd
       text: Home
     - resume.qmd
     - projects.qmd
     - teaching.qmd
    left:
     - icon: github
       href: https://github.com/ccani007
     - icon: linkedin
       href: https://www.linkedin.com/in/catalina-ca%C3%B1izares-escobar-2239114a/
     - icon: twitter
       href: https://twitter.com/catalinacaniza1?lang=en
  page-footer:
    right: 
     - icon: github
     - href: https://github.com/ccani007/ccani_website
    background: "#2c3c54"
    
format:
  html:
    theme: 
      - styles.scss
    mainfont: "Kumbh Sans"
    toc: true
    
  