---
title: "Teaching Resources"
execute: 
  echo: false
  message: false
  warning: false
---

I have developed a collection of educational materials that I'm excited to share with you. 


🥹 Best of all, these materials are completely free to use!     
👀  Whether you're a student, educator, or simply interested in expanding your knowledge, I invite you to explore the resources I've created.   


😎 *My goal is to continue creating interactive slides and other resources that can be used to enhance learning and knowledge-sharing worldwide.*


|  Content                                                                                                       |  Type of material                                                                                                         |  Presented to                                                                                  |  Where                            |
| -------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------- | --------------------------------- |
|  \`stringr\` and Regular Expressions                                                                           |  [Slides](https://ccani007.github.io/stringr_slides/#1)                                                                   |  Advanced R class                                                                              |  Florida International University |
|  \`stringr\` and Regular Expressions                                                                           |  [Lab](https://lcj9js-catalina-canizares.shinyapps.io/lab_str/?_ga=2.91765914.149069591.1678297151-1765971331.1678297151) |  Advanced R class                                                                              |  Florida International University |
|  \`RMarkdown\` for Reproducible Reports                                                                        |  [Slides](https://ccani007.github.io/advancedR_Slides/#1)                                                                 |  Advanced R class                                                                              |  Florida International University |
|  \`Quarto\` for Reproducible Reports                                                                           |  [Slides](https://rpubs.com/ccani007/991805)                                                                              |  [SWWR 27TH Annual Conference](https://sswr.confex.com/sswr/2023/webprogram/Session13742.html) |  Phoenix, AZ                      |
|  Introduction to Machine Learning                                                                              |  [Slides](https://catalina.quarto.pub/introduction-to-machine-learning/)                                                  |  R Computing for Health Sciences                                                               |  Florida International University |
|  Introduction to \`tidymodels\`                                                                                |  [Slides](https://catalina.quarto.pub/introduction-to-tidymodels/)                                                        |  R Computing for Health Sciences                                                               |  Florida International University |
|  Regularization Techniques: Ridge, Lasso and Elastic Net using \`tidymodels\`                                  |  [Slides](https://catalina.quarto.pub/regularization-techniques-ridge-lasso-and-elastic-net-using-tidymodels/)            |  R Computing for Health Sciences                                                               |  Florida International University |
|  Decision Trees Using \`tidymodels\`                                                                           |  [Slides](https://catalina.quarto.pub/decision-trees-using-tidymodels/)                                                   |  R Computing for Health Sciences                                                               |  Florida International University |
|  Random Forest Using \`tidymodels\`                                                                            |  [Slides](https://catalina.quarto.pub/random-forest-using-tidymodels/)                                                    |  R Computing for Health Sciences                                                               |  Florida International University |
|  KNN Using \`tidymodels\`                                                                                      |  [Slides](https://catalina.quarto.pub/knn-with-tidymodels/)                                                               |  R Computing for Health Sciences                                                               |  Florida International University |
|  Mastering effective data visualization with \`ggplot2\` in r: A hands on workshop for social work researchers |  [Slides](https://catalina.quarto.pub/ggplot-workshop/)                                                                   |  [SWWR 28th Annual Conference](https://sswr.confex.com/sswr/2024/webprogram/Session14318.html) |  Washington, DC                   |